### PR TITLE
Add a plugin

### PR DESCRIPTION
**Pull request by poppinlp**
Add Baidu Analytics plugin to README.md

### CODE REVIEW

**Comment by SamyPesse** [comment]
In the new version (2.0.0), I'm removing the list of plugins from the readme, instead we are listing the plugins at [plugins.gitbook.com](plugins.gitbook.com) (it will soon be released with an article about it)

**Comment by codepiano** [comment]
@SamyPesse 
Baidu is a search engine in China,and it sucks.
I will provide  this plugin after version 2.0.0 release.

**Comment by poppinlp** [comment]
@codepiano 
Plugin is already [done](https://github.com/poppinlp/gitbook-plugin-baidu).
And i agree Baidu Analytics is not as good as GA. But because of GFW, GA is not working well, so...you know...

**Comment by howiehu** [comment]
@poppinlp Nice work! It is a very helpful plugin for Chinese users.

**Comment by codepiano** [comment]
@poppinlp good job.I thought it's a issue.

**Pull request closed without merging**
