### PR TITLE
chore: bump scalar package

### PR DESCRIPTION
**Pull request by marclave**

### CODE REVIEW

**Review by emmerich — APPROVED** [review]
Looks good!

**Comment by marclave** [comment]
ah let me push up a changeset!

I was getting this error running `bun dev` on main

```
gitbook:dev: $ env-cmd -f ../../.env.local next dev
@gitbook/react-math:dev: $ tsc -w
gitbook:dev: Error: Failed to find .env file at path: ../../.env.local
gitbook:dev:     at getEnvFile (/Users/marclaventure/Software/gitbook-1/node_modules/env-cmd/dist/get-env-vars.js:40:19)
gitbook:dev: error: script "dev" exited with code 1
gitbook:dev: ERROR: command finished with error: command (/Users/marclaventure/Software/gitbook-1/packages/gitbook) /Users/marclaventure/.bun/bin/bun run dev exited (1)
gitbook#dev: command (/Users/marclaventure/Software/gitbook-1/packages/gitbook) /Users/marclaventure/.bun/bin/bun run dev exited (1)
```

do you get this @emmerich ?

**Comment by SamyPesse** [comment]
@marclave We have our `.env.local` file created with credentials stored in 1Password to download the premium icons set.
I thought it would not block development, but it looks like `env-cmd` crashes if it doesn't exist. Can you try creating an empty `.env.local`? I'll look at making it optional.

**Comment by marclave** [comment]
> @marclave We have our `.env.local` file created with credentials stored in 1Password to download the premium icons set. I thought it would not block development, but it looks like `env-cmd` crashes if it doesn't exist. Can you try creating an empty `.env.local`? I'll look at making it optional.

i added .env.local to root and it still didnt work 😭

**Review by SamyPesse — APPROVED** [review]

**Pull request merged**
