### PR TITLE
Improve header merge on page change

### LINKED ISSUE #782: Refreshing weird effect
Because of #759 and https://github.com/GitbookIO/gitbook/blob/master/theme/javascript/core/navigation.js#L25, there is now a weird refresh effect when we are replacing the `head`.

### PR DESCRIPTION
**Pull request by AaronO**
Prevents flickering (style reset)

Fixes #782, #838, #840

### CODE REVIEW

**Comment by AaronO** [comment]
This fixed the bug introduced by #759

**Comment by SamyPesse** [comment]
Thanks :+1: :wink: :heart:

**Comment by gaearon** [comment]
Woah, thank you! :dancers:

**Comment by GuGuss** [comment]
:+1:

**Comment by kylebrowning** [comment]
@SamyPesse @AaronO How can I download this to my local so that this issue is fixed?

Any chance of a 2.2.1 release?

**Pull request merged**
