### PR TITLE
Bump to lodash 3.5.0

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by AaronO** [comment]
@wcandillon Thanks for the PR, does this fix anything specific ?

**Comment by wcandillon** [comment]
@AaronO I thought it did but after further investigation I realized it didn't.

**Comment by AaronO** [comment]
@wcandillon It might fix some incompatibilities caused by `lodash`'s `3.0.0` release (we had a few of those), so it's probably worth updating.

I'll let @SamyPesse review and merge, he's overseeing the `2.0.0` release.

**Comment by wcandillon** [comment]
@AaronO I'm getting a really strange error in my project:
```
[19:01:22] Error: Error loading plugins: l,u,g,i,n,s. Run 'gitbook install' to install plugins from NPM.
    at Function.Plugin.fromList (/home/ubuntu/cellstore/node_modules/gitbook/lib/generate/plugin.js:240:45)
    at BaseGenerator.loadPlugins (/home/ubuntu/cellstore/node_modules/gitbook/lib/generate/generator.js:31:19)
    at wrapper [as loadPlugins] (/home/ubuntu/cellstore/node_modules/lodash/index.js:3057:19)
    at BaseGenerator.load (/home/ubuntu/cellstore/node_modules/gitbook/lib/generate/generator.js:25:17)
```

gitbook seems to use the base lodash dependency of my project. Do you know how I can prevent this?

**Comment by SamyPesse** [comment]
@wcandillon your error come from gitbook 1.5.0, the master is now 2.0.0-beta. You should run:

```
$ npm uninstall gitbook -g
$ npm install gitbook-cli
$ gitbook versions:install
```

**Comment by SamyPesse** [comment]
Thanks for the PR :+1:

**Comment by wcandillon** [comment]
@SamyPesse I'm using gulp to build the book. I'm still trying to figure out the programmatic way to do it.
For now I'm doing:
```javascript
gulp.task('gitbook:generate', ['gitbook:install'], function(){
    ffs.rmdirRecursiveSync('app/documentation');
    var book = new Book('documentation');
    return book.parse().then(function() {
            return book.generate();
    });
});
```

But I'm getting:
```bash
[15:24:31] Error: Generator 'site' doesn't exist
```

**Comment by wcandillon** [comment]
@SamyPesse Now if I do:

```javascript
    var book = new Book('documentation');
    return book.parse().then(function() {
        return book.generate('website');
    });
```

The book generates fine but there seems to be an event point that is not released.

**Pull request merged**
