### PR TITLE
Version 3.0.0

### LINKED ISSUE #537: Any way to remove .html extension from URL?
As an example:

For http://help.gitbook.io/book/errors.html

Can we generate it as http://help.gitbook.io/book/errors/index.html , which will give cleaner URLs like http://help.gitbook.io/book/errors/  ?

### LINKED ISSUE #744: custom /images directory in root not copied to output?
i am using multilanguage so i have an /en directory where my content resides. 
next to that directory i put an /images directory. referencing images from that does not work as it seems the directory is not being copied to the book output. is that by design? is there anything i can do about it?

### LINKED ISSUE #776: Add anchors to summary
Summary.md only allow to add links to other markdown files at all, but it's not possible to add links to subititles inside of them, making it mandatory that each entry on the summary needs to be on its own markdown file and start in its own page/chapter when its not always necesary.

### LINKED ISSUE #788: Styles in root folder not working with multilanguage books
There is a possibility to include the styles by adding them to the definition in `book.json`.
We have a multilanguage book, and I have noticed that adding the styles will work perfectly fine if they are added to one of the language folders.
We would like the styles to apply to all the languages and not be placed in each language separately and currently we can't do that. The folder `styles`, placed in the root folder isn't being transferred to the generated book. I have tried defining the styles in various ways, for example: `./../styles/website.css`, `/styles/website.css`, `../styles/website.css`. I have also tried moving the file to the root folder and changing the definition in `book.json`. None of this works.

We are using gitbook@2.1.0

### PR DESCRIPTION
**Pull request by SamyPesse**
- [x] Simpler JS APIs (in GitBook itself and plugins)
- [x] Improvements for Glossary (`GLOSSARY.md`)
     - [x] Generate glossary as a normal page
     - [x] Add class `.no-glossary` to avoid annotating in it
     - [x] Don't annotate in headings
- [ ] Improvements for Languages (`LANGS.md`)
    - [ ] Fix #788
    - [x] Fix #744
    - [x] Remove plugins from language books (list of plugins should be global for the entire book)
- [x] Improvements for Summary (`SUMMARY.md`)
     - [x] Allow anchor entries, ex: `* [Entry](test.md#hello)` (Fix #776)
     - [x] Allow multiple parts/sections in SUMMARY
     - [x] Allow external entries
     - [x] No longer required
- [x] Page
     - [x] Optmize urls when links to a `README.md` (Fix #537)
     - [x] Text direction can change between pages (`ltr` to `rtl`)
- [x] Templating
     - [ ] Allow single tag block (exemple for `codesnippet` plugin)
     - [x] Cleanup context
     - [ ] Update to `nunjucks@3`
     - [x] date filters
- [x] Documentation use-case, where book is stored in a `docs` folder
- [x] Theming
     - [x] Default theme should be stored in an external repository (https://github.com/GitbookIO/theme-default)
     - [x] Author can specify a theme in its `book.json`
     - [x] Author can extend his theme by creating a `_layouts` folder
     - [x] i18n templating filter  in the core
     - [x] Merge templating engine with the book's one
- Markdown
     - [x] Switch to `markdown-it` instead of `kramed` ?
            - [ ] `[ALink]:..` no supported (https://gist.github.com/SamyPesse/c2875343878f21338b14)
- Tests
     - [ ] Fix tests on Windows

#### Change Log

https://github.com/GitbookIO/gitbook/blob/3.0.0/CHANGES.md

### CODE REVIEW

**Comment by nateberkopec** [comment]
:clap:

**Comment by nagim** [comment]
:cool:

**Comment by nagim** [comment]
Some improvement ideas for Glossary:
- Do not link glossary items in titles
- Use more subtle format, one that separates glossary items from other links (e.g.: no underline and less vivid text color)
- Configurable overload functionality: right now, if we define multiple meaning/explanation for a glossary item, it will display all of them in the tooltip. It would be useful to be able to assign an attribute or some variable to the different explanations, then use this attribute in the metadata of the document. This way, one explanation could take precedence over the other(s), when displaying the tooltip. This is useful when you have an abbreviation, which means different things in different topics, and we want to avoid confusion.

**Comment by nagim** [comment]
This keeps getting better. Keep up! :smile:

**Comment by jinzhu** [comment]
Could I build a usable 3.0.0 on my local, needs some features that only exists in v3 (eg: anchor entries), but seems like the builded pages has wrong style.

**Comment by nagim** [comment]
Hi Samy! Will #1159 be supported in 3.0.0?

**Comment by nagim** [comment]
:bow: :+1:

**Comment by nagim** [comment]
:clap:

**Comment by SamyPesse** [comment]
:beers: :fireworks: :birthday: 

We are going to release the first pre-release of GitBook v3 today, with support on GitBook.com released tomorrow.
GitBook v3 will stay in a alpha/beta stage for ~1month, till we help developers adapt plugins, etc.

You'll be able to easily switch from GitBook v2 to GitBook v3 in the GitBook.com UI.

**Comment by nagim** [comment]
Really great work guys in such a short time!
Hats off! :+1: :beers:

**Comment by Jayin** [comment]
:clap: :clap:

**Comment by davis** [comment]
how do we use gitbook 3.0.0-pre.3?

**Comment by davis** [comment]
(with gitbook cli)

**Comment by dorako321** [comment]
@davis gitbook v3 is not available in npm command yet.
we have to clone gitbook repository, and use gitbook-cli alias command. 

plz, check this page.
https://github.com/GitbookIO/gitbook-cli

> Use a local folder as a GitBook version (for developement)
> $ gitbook alias ./mygitbook latest

**Pull request merged**
