### PR TITLE
Fixed two issues for handling git URLs for plugins

### PR DESCRIPTION
**Pull request by ryanswanson**
Fixed two issues for handling git URLs for plugins that are published to git repositories rather than on npmjs.org.

Fixed issue in pluginDependency to dereference 'name' and 'version' using Immutable Map.get(...) accessors since config values are now wrapped by Immutable.fromJS(...) in config.js > setValue(...).  Added associated unit test.

Fixed issue in resolveVersion where a plugin may be using a git URL rather than a semver for the version portion of the plugin config definition.  In addition, refactored the resolveVersion function into a new module to allow for unit testing.  Added associated unit test.

### CODE REVIEW

**Comment by ryanswanson** [comment]
**Background**
In creating my first gitbook plugin, I initially developed locally using `npm link gitbook-plugin-myplugin` for the dependency.  My book.json in the main project could simply list `'myplugin'` as a string.

Once I was ready to publish to a private git URL to share with our team, I found that the [object-based configuration with name/value keys described by Samy](https://github.com/GitbookIO/gitbook/issues/1093#issuecomment-170586843) appeared to no longer function - yielding the following error message:
```shell
info: installing plugin "myplugin"

Error: Registry returned 404 for GET on https://registry.npmjs.org/gitbook-plugin-myplugin
```
This led to the fix in pluginDependency.js.

I also learned that a compound string syntax would also work in the meantime: `myplugin@git+https://github.com/YourCompany/myplugin.git`.

Unfortunately, the same error displayed (404 while attempting to load from npmjs.org), but now due to an issue in the resolveVersion method of installPlugins.js.  This methods uses the nmp `view` command, which is valid when the configured version is a semver; but not when the config version is used to support git URLs.  The semver.validRange(...) method (luckily, already imported in that file) provided the needed conditional to bypass processing non-semver *versions*.

Hope you don't mind the refactor to introduce a new test for resolveVersion.

Cheers,
Ryan

**Comment by SamyPesse** [comment]
Looks good, Thanks 👍

**Comment by SamyPesse** [comment]
I'll just make a few changes on master so that `installPlugin` and `resolvePlugin` use `PluginDependency` instead of `Plugin`.

**Comment by ryanswanson** [comment]
Great!  Glad to help.  Appreciate the quick response and version bump so I can make use of it today.

**Pull request merged**
