### PR TITLE
Improvements for ebooks

### LINKED ISSUE #791: Changing font size in iBooks iPhone app changes nothing
(Bug reported to gitbook.com)

### LINKED ISSUE #899: Font for header and footer in PDF is different
When generating a pdf, the header and footer font is quite different than the content of the page.

Is there any setting to set in book.json to fix this?

Ive tried 

```
    "pluginsConfig": {
        "fontSettings": {
            "theme": "white",
            "family":"sans",
            "size": 1
        }
    }
```

and 
```
    "pdf": {
        "pageNumbers": true,
        "fontSize": 12,
        "fontFamily": "sans",
        "paperSize": "a4",
        "margin": {
            "right": 62,
            "left": 62,
            "top": 36,
            "bottom": 36
        },
        "headerTemplate": "_TITLE_ | _PAGENUM_",
        "footerTemplate": "Acquia.com | 53 State Street, 10th Floor, Boston, MA 02109"
    },
```

But it still looks different 

cursor_and_llnl-aug-2015-arch_pdf__page_1_of_41_

### LINKED ISSUE #938: Don't put headers at end of page
As you can see on the image, GitBook has put a header at the end of a page, while it should have detect it and move to the next page. Maybe this can be fixed by wrapping each header and their text section with a div...

### LINKED ISSUE #951: Ebook links and code highlighting on Kindle not very legible
On a grayscale device such as the Kindle, links and code highlighting converts to a lighter grey color, which is hard to read. Would recommend using black (#000) and/or bold. Related to: https://github.com/GitbookIO/gitbook/issues/784

See (sorry for rotation):

### PR DESCRIPTION
**Pull request by SamyPesse**
- [x] Better header/footer for PDF (Fix #899)
     - [x] Inline style from `ebook.css` and `<type>.css` into header and footer
- [x] Cleaner table of contents
     - [x] Support rtl for toc
- [x] Better handling of page breaks (Fix #938)
- [x] Better colors for mobi (Fix #951)
- [x] Handle font-size from reader in epub (Fix #791)

### CODE REVIEW

**Comment by SamyPesse** [comment]
Preview of the new footer/header:

screen shot 2015-10-03 at 17 34 23

**Comment by SamyPesse** [comment]
Screenshot of the new toc:

screen shot 2015-10-05 at 22 53 56

**Comment by SamyPesse** [comment]
Glossary on PDF:

screen shot 2015-10-06 at 09 58 17

**Comment by SamyPesse** [comment]
Links on mobi are now black:

screen shot 2015-10-06 at 11 08 44

**Comment by onevcat** [comment]
Amazing! Thanks for the hard work!

**Pull request merged**
