### PR TITLE
Number Single Level books as multiple levels.

### LINKED ISSUE #1301: 3 pre.14: All items start with level 1.x
When I view the level numbers, everything starts at a 1.x level but the summary file doesn't have any nesting. To my eyes it looks just like there's an extra "1." before every item.
screen shot 2016-05-12 at 2 20 45 am

### PR DESCRIPTION
**Pull request by cycomachead**
Fix #1301

This makes it so that a single level book will have chapters show as
"1.", "2." and so on, making single part books appear the same as
before.

Note that the smallest way to make this change causes the `level`
property to be an integer for single part books. I'm not 100% sure this
is desirable, but so far it didn't seem to cause complications.

### CODE REVIEW

**Comment by SamyPesse** [comment]
Thanks, there are some indentation issues (we are using 4 spaces).

Also can you add a test in `lib/models/__tests__/summary.js`?

**Comment by cycomachead** [comment]
> Thanks, there are some indentation issues (we are using 4 spaces).

Not sure what happened there... I'll fix that up.

> Also can you add a test in lib/models/__tests__/summary.js?

Sure. I'll probably get to that in a day or two.

**Comment by Soreine** [comment]
Levels are used inside the library to navigate the `Summary`. If we are going this route, we need to make sure the levels are consistent with the `Summary` structure. As long as the articles are within a single, untitled part, the levels should render that.
Your initial issue is not a logic matter, but a display matter. So I'll suggest to fix this at the output generation level. For convenience, we could provide some function with the `Summary` to return a _displayed level_.

```ts
/**
 * @param {Summary} summary
 * @param {SummaryArticle | SummaryPart} entry
 * @return {String} The displayed level (1 instead of 1.1 when adequate)
 */
function displayedLevel(summary, entry) {
    ...
}
```

I wonder what should be the behavior for books with a summary like this:

```md
# Summary

* Chapter 1
* Chapter 2

## Appendix Part

* Chapter 3
```

Something like that ? : 

```
1.1 Chapter 1
1.2 Chapter 2
2. Appendix Part
2.1 Chapter 3
```

**Comment by noerw** [comment]
any progress on this issue?

**Comment by zq99299** [comment]
啥时候能解决哇。现在的 1.1 太难受了
When can solve wow. Now 1.1 too uncomfortable

**Comment by colingonglin** [comment]
Almost one year passed...
When will this issue be resolved?

**Comment by pablo14** [comment]
Dear @cycomachead  do you have a workaround to avoid this issue? Thanks:)

**Comment by huarse** [comment]
+1, `1.1`, `1.2` is so uncomfortable, I prefer to `1`, `2`

**Comment by crifan** [comment]
+1
Hope fix it ASAP！

**Comment by wajchina** [comment]
This issue was not resoled yet, is there any progress on this issue?

**Pull request closed without merging**
