### PR TITLE
Adding data-uri support for PNG Images in Books

### PR DESCRIPTION
**Pull request by tiefox**
Hi. This pull request adds support for png images with data-uri.
For instance

```
![image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
```
They were being treated as external URLs and failing to render

### CODE REVIEW

**Comment by SamyPesse** [comment]
Great PR 🍻  👍 , but ... we pushed a rewrite of GitBook using immutable models, etc.

Can you take a look to adapt your PR to the new master ? Otherwise, I'll take a look in the coming days.

**Comment by SamyPesse** [comment]
BTW here are the new files that should be concerned:

- https://github.com/GitbookIO/gitbook/blob/master/lib/utils/location.js
- https://github.com/GitbookIO/gitbook/blob/master/lib/output/modifiers/fetchRemoteImages.js
- https://github.com/GitbookIO/gitbook/blob/master/lib/output/modifiers/resolveImages.js

And a new modifier should be created to extract inline image as png file, then it should be added to https://github.com/GitbookIO/gitbook/blob/master/lib/output/modifiers/inlineAssets.js

**Comment by SamyPesse** [comment]
Closed in favor of #1259

Thanks @tiefox, @jpreynat adapted your changes.

**Comment by tiefox** [comment]
hi @SamyPesse and @jpreynat ! Thanks a lot for adjust the code for the PR, I'm having a crazy week at work and could not find time to work on it. :) 👍

**Pull request closed without merging**
